# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"aPyopticum": "00_core.ipynb",
         "ureg": "00_core.ipynb",
         "pc": "00_core.ipynb"}

modules = ["Pyopticum.py"]

doc_url = "https://jlovick.github.io/pyopticum/"

git_url = "https://github.com/jlovick/pyopticum/tree/master/"

def custom_doc_links(name): return None
