# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).


from __future__ import print_function


__all__ = ['aPyopticum']

# Cell
#nbdev_comment from __future__ import print_function
import random

class aPyopticum:
    """
    Initial class to hold optical formula's etc

    """
    def __init__(self):
        self.data = []

    def say_hello(self,to):
        "Say hello to someone"
        return f" hello {to}!"